import { Worker, Job } from 'bullmq'
import { getRedis } from '../lib/redis'
import { prisma } from '../lib/prisma'
import { logger } from '../lib/logger'
import { TaskRepository } from '../repositories/task.repository'
import { RepositoryRepository } from '../repositories/repository.repository'
import { GitHubService } from '../lib/github'
import { applyDiff } from '../lib/diff'
import type { FileChange } from '@codemind/shared'

interface PatchJobData {
  taskId: string
  agentJobId: string
}

const taskRepo = new TaskRepository(prisma)
const repoRepo = new RepositoryRepository(prisma)

async function emit(job: Job, event: object) {
  await job.updateProgress(event)
}

export function startPatchWorker() {
  const worker = new Worker<PatchJobData>('patch-queue', async (job) => {
    const { taskId, agentJobId } = job.data

    const task = await taskRepo.findById(taskId)
    if (!task) throw new Error(`Task ${taskId} not found`)

    const codingJob = await taskRepo.findAgentJobById(agentJobId)

    const fileChanges = (codingJob?.fileChanges as FileChange[] | null) ?? null
    const hasMultiFile = Array.isArray(fileChanges) && fileChanges.length > 0
    const hasSingleFile = !!codingJob?.patchedContent && !!codingJob.primaryFilePath

    if (!hasMultiFile && !hasSingleFile) {
      throw new Error('No patched content available')
    }

    const repo = await repoRepo.findById(task.repositoryId)
    if (!repo) throw new Error('Repository not found')
    if (!repo.githubToken) throw new Error('No GitHub token — cannot create PR')

    const github = new GitHubService(repo.githubToken)

    await emit(job, { type: 'log', message: '  Getting base branch SHA...', level: 'info' })
    const baseSha = await github.getBranchSha(repo.owner, repo.name, repo.defaultBranch)

    const slug = task.title.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 40)
    const branchName = `ai/${slug}-${task.id.slice(-6)}`

    await emit(job, { type: 'log', message: `  Creating branch: ${branchName}`, level: 'info' })
    await github.createBranch(repo.owner, repo.name, branchName, baseSha)

    // Determine files to commit: prefer multi-file payload, fall back to single-file
    let filesToCommit: { path: string; content: string }[]

    if (hasMultiFile) {
      filesToCommit = []
      for (const fc of fileChanges!) {
        if (fc.operation === 'create') {
          if (fc.content) filesToCommit.push({ path: fc.path, content: fc.content })
        } else {
          // Fetch the actual current file from GitHub and apply the diff to get correct content
          try {
            await emit(job, { type: 'log', message: `  Fetching current ${fc.path}...`, level: 'info' })
            const original = await github.getFileContent(repo.owner, repo.name, fc.path)
            const patched = applyDiff(original, fc.diff ?? '')
            filesToCommit.push({ path: fc.path, content: patched })
          } catch (err) {
            logger.warn({ path: fc.path, err }, 'Could not fetch/apply diff — skipping file')
          }
        }
      }
      if (filesToCommit.length === 0) throw new Error('No files could be prepared for commit')
    } else {
      filesToCommit = [{ path: codingJob!.primaryFilePath!, content: codingJob!.patchedContent! }]
    }

    // Commit each file (create or update depending on whether it exists on the branch)
    for (const file of filesToCommit) {
      const fileSha = await github.getFileSha(repo.owner, repo.name, file.path, repo.defaultBranch)
      await emit(job, { type: 'log', message: `  Committing ${file.path}...`, level: 'info' })
      await github.commitFile(repo.owner, repo.name, {
        path: file.path,
        content: file.content,
        message: `feat: ${task.title}`,
        branch: branchName,
        sha: fileSha, // undefined for new files — GitHub API creates them; defined for updates
      })
    }

    // Build PR body from review summary
    const reviewJob = task.agentJobs.find((j) => j.agentType === 'REVIEW')
    const prBody = [
      `## CodeMind AI Change`,
      ``,
      `**Task:** ${task.title}`,
      `**Type:** ${task.changeType}`,
      `**Attempt:** ${task.attempt}`,
      `**Files changed:** ${filesToCommit.length}`,
      ``,
      `### Description`,
      task.description,
      ``,
      `### Agent Explanation`,
      codingJob?.explanation ?? '_No explanation provided._',
      ``,
      reviewJob?.reviewSummary ? `### Review Summary\n${reviewJob.reviewSummary}` : '',
      ``,
      `---`,
      `*Generated by [CodeMind](https://github.com/codemind)*`,
    ].filter(Boolean).join('\n')

    await emit(job, { type: 'log', message: '  Opening Pull Request...', level: 'info' })
    const { data: pr } = await github.createPR(repo.owner, repo.name, {
      title: `[AI] ${task.title}`,
      body: prBody,
      head: branchName,
      base: repo.defaultBranch,
    })

    await taskRepo.createPullRequest({
      taskId,
      repoFullName: repo.fullName,
      prNumber: pr.number,
      branchName,
      prUrl: pr.html_url,
      title: pr.title,
    })

    await taskRepo.updateStatus(taskId, 'DONE')

    await emit(job, { type: 'done', prUrl: pr.html_url, prNumber: pr.number })
    logger.info({ taskId, prUrl: pr.html_url, fileCount: filesToCommit.length }, 'PatchWorker: PR created')

    return { prUrl: pr.html_url, prNumber: pr.number }
  }, {
    connection: getRedis() as any,
    concurrency: 2,
  })

  worker.on('failed', async (job, err) => {
    const message = err instanceof Error ? err.message : String(err)
    logger.error({ jobId: job?.id, err }, 'Patch worker failed')
    if (job?.data?.taskId) {
      await taskRepo.updateStatus(job.data.taskId, 'FAILED').catch(() => {})
    }
    if (job?.data?.agentJobId) {
      await taskRepo.appendJobLog(job.data.agentJobId, `PR creation failed: ${message}`).catch(() => {})
    }
  })
  logger.info('PatchWorker started')
  return worker
}
