import { Worker, Job } from 'bullmq'
import { getRedis } from '../lib/redis'
import { prisma } from '../lib/prisma'
import { logger } from '../lib/logger'
import { TaskRepository } from '../repositories/task.repository'
import { RepositoryRepository } from '../repositories/repository.repository'
import { GitHubService } from '../lib/github'

interface PatchJobData {
  taskId: string
  agentJobId: string
}

const taskRepo = new TaskRepository(prisma)
const repoRepo = new RepositoryRepository(prisma)

async function emit(job: Job, event: object) {
  await job.updateProgress(event)
}

export function startPatchWorker() {
  const worker = new Worker<PatchJobData>('patch-queue', async (job) => {
    const { taskId, agentJobId } = job.data

    const task = await taskRepo.findById(taskId)
    if (!task) throw new Error(`Task ${taskId} not found`)

    const codingJob = await taskRepo.findAgentJobById(agentJobId)
    if (!codingJob?.patchedContent || !codingJob.primaryFilePath) {
      throw new Error('No patched content available')
    }

    const repo = await repoRepo.findById(task.repositoryId)
    if (!repo) throw new Error('Repository not found')
    if (!repo.githubToken) throw new Error('No GitHub token — cannot create PR')

    const github = new GitHubService(repo.githubToken)

    await emit(job, { type: 'log', message: '  Getting base branch SHA...', level: 'info' })
    const baseSha = await github.getBranchSha(repo.owner, repo.name, repo.defaultBranch)

    const slug = task.title.toLowerCase().replace(/[^a-z0-9]/g, '-').slice(0, 40)
    const branchName = `ai/${slug}-${task.id.slice(-6)}`

    await emit(job, { type: 'log', message: `  Creating branch: ${branchName}`, level: 'info' })
    await github.createBranch(repo.owner, repo.name, branchName, baseSha)

    // Get current file SHA for update (required by GitHub API)
    const fileSha = await github.getFileSha(repo.owner, repo.name, codingJob.primaryFilePath, repo.defaultBranch)

    await emit(job, { type: 'log', message: `  Committing ${codingJob.primaryFilePath}...`, level: 'info' })
    await github.commitFile(repo.owner, repo.name, {
      path: codingJob.primaryFilePath,
      content: codingJob.patchedContent,
      message: `feat: ${task.title}`,
      branch: branchName,
      sha: fileSha,
    })

    // Build PR body from review summary
    const reviewJob = task.agentJobs.find((j) => j.agentType === 'REVIEW')
    const prBody = [
      `## CodeMind AI Change`,
      ``,
      `**Task:** ${task.title}`,
      `**Type:** ${task.changeType}`,
      `**Attempt:** ${task.attempt}`,
      ``,
      `### Description`,
      task.description,
      ``,
      `### Agent Explanation`,
      codingJob.explanation ?? '_No explanation provided._',
      ``,
      reviewJob?.reviewSummary ? `### Review Summary\n${reviewJob.reviewSummary}` : '',
      ``,
      `---`,
      `*Generated by [CodeMind](https://github.com/codemind)*`,
    ].filter(Boolean).join('\n')

    await emit(job, { type: 'log', message: '  Opening Pull Request...', level: 'info' })
    const { data: pr } = await github.createPR(repo.owner, repo.name, {
      title: `[AI] ${task.title}`,
      body: prBody,
      head: branchName,
      base: repo.defaultBranch,
    })

    await taskRepo.createPullRequest({
      taskId,
      repoFullName: repo.fullName,
      prNumber: pr.number,
      branchName,
      prUrl: pr.html_url,
      title: pr.title,
    })

    await taskRepo.updateStatus(taskId, 'DONE')

    await emit(job, { type: 'done', prUrl: pr.html_url, prNumber: pr.number })
    logger.info({ taskId, prUrl: pr.html_url }, 'PatchWorker: PR created')

    return { prUrl: pr.html_url, prNumber: pr.number }
  }, {
    connection: getRedis() as any,
    concurrency: 2,
  })

  worker.on('failed', (job, err) => logger.error({ jobId: job?.id, err }, 'Patch worker failed'))
  logger.info('PatchWorker started')
  return worker
}
